server:
  port: 8083

spring:
  application:
    name: authorization-service

  #Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/authorization
    username: root
    password: rootuser

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect